matrix:
  include:
    - os: osx
      env: ACTION=iOS
    - os: osx
      env: ACTION=OSX
    - os: osx
      env: ACTION=tvOS
    - os: osx
      env: ACTION=watchOS
    # - os: osx
    #   env: ACTION=carthage
    - os: osx
      env: ACTION=cocoapods

language: objective-c
osx_image: xcode8

script:
  - git submodule update --init --recursive
  - make install-$ACTION && make test-$ACTION
